package etl;
import estructuras.*;import model.*;import java.util.*;
public class Transform{public ListaEnlazada<Estudiante> estudiantes=new ListaEnlazada<>();public ListaEnlazada<Asignatura> asignaturas=new ListaEnlazada<>();public ListaEnlazada<Matricula> matriculas=new ListaEnlazada<>();public ListaEnlazada<Prerequisito> prerequisitos=new ListaEnlazada<>();public Pila<ErrorETL> errores=new Pila<>();public Map<String,Integer> stats=new HashMap<>();Set<String>ids=new HashSet<>(),cods=new HashSet<>();
 void err(String f,String id,String m,String d){errores.apilar(new ErrorETL(f,id,m,d));stats.put(m,stats.getOrDefault(m,0)+1);}String norm(String s){return s.trim().replaceAll("\\s+"," ");}
 public void estudiantes(Cola<String[]>q){while(!q.estaVacia()){String[]x=q.desencolar();if(x.length<7){err("estudiantes.csv","?","DATOS_INCOMPLETOS","7 campos requeridos");continue;}String id=norm(x[0]);try{int e=Integer.parseInt(x[3].trim()),s=Integer.parseInt(x[5].trim());double p=Double.parseDouble(x[6].trim());if(!id.matches("\\d{10}")){err("estudiantes.csv",id,"IDENTIFICADOR_INCORRECTO","10 dígitos requeridos");continue;}if(!ids.add(id)){err("estudiantes.csv",id,"DUPLICADO","ID repetido");continue;}if(e<16||e>80){err("estudiantes.csv",id,"RANGO_EDAD","16..80");continue;}if(s<1||s>12){err("estudiantes.csv",id,"RANGO_SEMESTRE","1..12");continue;}if(p<0||p>10){err("estudiantes.csv",id,"RANGO_PROMEDIO","0..10");continue;}if(norm(x[1]).isEmpty()||norm(x[2]).isEmpty()||norm(x[4]).isEmpty()){err("estudiantes.csv",id,"CAMPO_OBLIGATORIO","Campo vacío");continue;}estudiantes.insertarFinal(new Estudiante(id,norm(x[1]),norm(x[2]),e,norm(x[4]),s,p));}catch(Exception z){err("estudiantes.csv",id,"FORMATO_NUMERICO","Dato numérico inválido");}}}
 public void asignaturas(Cola<String[]>q){while(!q.estaVacia()){String[]x=q.desencolar();if(x.length<4){err("asignaturas.csv","?","DATOS_INCOMPLETOS","4 campos");continue;}try{String c=norm(x[0]);int n=Integer.parseInt(x[2].trim()),cr=Integer.parseInt(x[3].trim());if(!cods.add(c)){err("asignaturas.csv",c,"DUPLICADO","Código repetido");continue;}asignaturas.insertarFinal(new Asignatura(c,norm(x[1]),n,cr));}catch(Exception z){err("asignaturas.csv",x[0],"FORMATO_NUMERICO","Dato inválido");}}}
 boolean existeE(String id){for(int i=0;i<estudiantes.tamanio();i++)if(estudiantes.obtener(i).getId().equals(id))return true;return false;}boolean existeA(String c){for(int i=0;i<asignaturas.tamanio();i++)if(asignaturas.obtener(i).getCodigo().equals(c))return true;return false;}
 public void matriculas(Cola<String[]>q){while(!q.estaVacia()){String[]x=q.desencolar();if(x.length<4){err("matriculas.csv","?","DATOS_INCOMPLETOS","4 campos");continue;}if(!existeE(x[0])||!existeA(x[1])){err("matriculas.csv",x[0],"REFERENCIA_INCONSISTENTE","Estudiante/asignatura inexistente");continue;}if(!x[3].equalsIgnoreCase("ACTIVA")&&!x[3].equalsIgnoreCase("RETIRADA")){err("matriculas.csv",x[0],"ESTADO_INVALIDO","Estado no reconocido");continue;}matriculas.insertarFinal(new Matricula(x[0],x[1],x[2],x[3].toUpperCase()));}}
 public void prerequisitos(Cola<String[]>q){while(!q.estaVacia()){String[]x=q.desencolar();if(x.length<2||!existeA(x[0])||!existeA(x[1]))err("prerrequisitos.csv",x.length>0?x[0]:"?","REFERENCIA_INCONSISTENTE","Asignatura inexistente");else prerequisitos.insertarFinal(new Prerequisito(x[0],x[1]));}}
}
